Repository Jeffrey86Wan/CITS5505_Group48, pull requests merged in 2025-05, with the labels that each got.

#21 feat: add login and register pages
  .flaskenv
  app.py
  requirements.txt
  routes/main.py
  templates/auth/login.html
  templates/auth/register.html
  templates/components/auth_base.html
  templates/components/dashboard_base.html
  templates/components/navigator_base.html
  templates/main/flow.html
  templates/main/index.html
  templates/main/public.html
  templates/main/record.html
  templates/main/report.html
Labels: front-end

#25 refactor: refactor auth pages by jinja templates
  expensemanager.db
  static/css/styles.css
  static/img/icons/google.svg
  static/js/login.js
  templates/auth/login.html
  templates/auth/register.html
  templates/components/auth_base.html
Labels: bug, front-end

#29 fix: fix the wrong log out logic #28
  app.py
  expensemanager.db
  requirements.txt
  routes/auth/login.py
  static/js/logout.js
  templates/auth/login.html
  templates/auth/logout.html
  templates/auth/register.html
Labels: bug

#37 feat:finish munually add function
  routes/record.py
  templates/main/record.html
Labels: enhancement, front-end, back-end

#45 feat: finished home page with real data
  expensemanager.db
  models/__init__.py
  models/blog.py
  models/record_list.py
  routes/__init__.py
  routes/api.py
  routes/auth/login.py
  routes/index.py
  routes/record.py
  static/img/default_avator.png
  static/js/index.js
  templates/components/dashboard_base.html
  templates/components/navigator_base.html
  templates/main/index.html
  templates/main/record.html
  templates/main/record_list.html
Labels: enhancement

#44 add selenium test
  tests/__init__.py
  tests/test_imports.py
  tests/test_selenium.py
Labels: testing

#57 feat: add two error pages 404 and 500
  app.py
  templates/errors/404.html
  templates/errors/500.html
Labels: enhancement
